#include "block.hpp"

enum TextureIndex{
    Air = 0,
    GrassDirt,
    Dirt,
    Grass,
    Stone,
    Sand,
    OakLogAround,
    OakLogTop,
    OakWood,
    Water,
    OakLeaves,
    CactusAround,
    CactusTop,
    SpruceLogAround,
    SpruceLogTop,
    SpruceLeaves,
    WinterGrassDirt,
    WinterGrass,
    BirchLogAround,
    BirchLogTop,
    BirchLeaves,
    DiamondOre,
    GoldenOre,
    RedstoneOre,
    Coblestone,
    DiamondBlock,
    GoldenBlock,
    RedstoneBlock,
    EmeraldBlock,
    EmeraldOre,
    SpruceWood,
    BirchWood
};

static BlockTextures s_TextureTable[] = {
    {
        Air,
        Air,
        Air,
        Air,
        Air,
        Air
    },
    {
        GrassDirt,
        GrassDirt,
        GrassDirt,
        GrassDirt,
        Grass,
        Dirt
    },
    {
        WinterGrassDirt,
        WinterGrassDirt,
        WinterGrassDirt,
        WinterGrassDirt,
        WinterGrass,
        Dirt
    },
    {
        Dirt,
        Dirt,
        Dirt,
        Dirt,
        Dirt,
        Dirt
    },
    {
        Stone,
        Stone,
        Stone,
        Stone,
        Stone,
        Stone
    },
    {
        Coblestone,
        Coblestone,
        Coblestone,
        Coblestone,
        Coblestone,
        Coblestone,
    },
    {
        Sand,
        Sand,
        Sand,
        Sand,
        Sand,
        Sand
    },
    {
        CactusAround,
        CactusAround,
        CactusAround,
        CactusAround,
        CactusTop,
        CactusTop
    },
    {
        Water,
        Water,
        Water,
        Water,
        Water,
        Water
    },
    {
        OakLogAround,
        OakLogAround,
        OakLogAround,
        OakLogAround,
        OakLogTop,
        OakLogTop
    },
    {
        OakWood,
        OakWood,
        OakWood,
        OakWood,
        OakWood,
        OakWood
    },
    {
        OakLeaves,
        OakLeaves,
        OakLeaves,
        OakLeaves,
        OakLeaves,
        OakLeaves
    },
    {
        SpruceLogAround,
        SpruceLogAround,
        SpruceLogAround,
        SpruceLogAround,
        SpruceLogTop,
        SpruceLogTop
    },
    {
        SpruceWood,
        SpruceWood,
        SpruceWood,
        SpruceWood,
        SpruceWood,
        SpruceWood
    },
    {
        SpruceLeaves,
        SpruceLeaves,
        SpruceLeaves,
        SpruceLeaves,
        SpruceLeaves,
        SpruceLeaves
    },
    {
        BirchLogAround,
        BirchLogAround,
        BirchLogAround,
        BirchLogAround,
        BirchLogTop,
        BirchLogTop
    },
    {
        BirchWood,
        BirchWood,
        BirchWood,
        BirchWood,
        BirchWood,
        BirchWood
    },
    {
        BirchLeaves,
        BirchLeaves,
        BirchLeaves,
        BirchLeaves,
        BirchLeaves,
        BirchLeaves
    },
    {
        DiamondOre,
        DiamondOre,
        DiamondOre,
        DiamondOre,
        DiamondOre,
        DiamondOre,
    },
    {
        GoldenOre,
        GoldenOre,
        GoldenOre,
        GoldenOre,
        GoldenOre,
        GoldenOre,
    },
    {
        RedstoneOre,
        RedstoneOre,
        RedstoneOre,
        RedstoneOre,
        RedstoneOre,
        RedstoneOre,
    },
    {
        EmeraldOre,
        EmeraldOre,
        EmeraldOre,
        EmeraldOre,
        EmeraldOre,
        EmeraldOre,
    },
    {
        DiamondBlock,
        DiamondBlock,
        DiamondBlock,
        DiamondBlock,
        DiamondBlock,
        DiamondBlock,
    },
    {
        GoldenBlock,
        GoldenBlock,
        GoldenBlock,
        GoldenBlock,
        GoldenBlock,
        GoldenBlock,
    },
    {
        RedstoneBlock,
        RedstoneBlock,
        RedstoneBlock,
        RedstoneBlock,
        RedstoneBlock,
        RedstoneBlock,
    },
    {
        EmeraldBlock,
        EmeraldBlock,
        EmeraldBlock,
        EmeraldBlock,
        EmeraldBlock,
        EmeraldBlock,
    },
};

BlockTextures GetBlockTextures(Block block){
    return s_TextureTable[(size_t)block];
}