#include "block.hpp"

enum TextureIndex{
    Air = 0,
    GrassDirt,
    Dirt,
    Grass,
    Stone,
    Sand,
    OakLogAround,
    OakLogTop,
    OakWood,
    Water,
    OakLeaves,
    CactusAround,
    CactusTop,
    SpruceLogAround,
    SpruceLogTop,
    SpruceLeaves,
    WinterGrassDirt,
    WinterGrass,
    BirchLogAround,
    BirchLogTop,
    BirchLeaves
};

static BlockTextures s_TextureTable[] = {
    {
        Air,
        Air,
        Air,
        Air,
        Air,
        Air
    },
    {
        GrassDirt,
        GrassDirt,
        GrassDirt,
        GrassDirt,
        Grass,
        Dirt
    },
    {
        Dirt,
        Dirt,
        Dirt,
        Dirt,
        Dirt,
        Dirt
    },
    {
        Stone,
        Stone,
        Stone,
        Stone,
        Stone,
        Stone
    },
    {
        Sand,
        Sand,
        Sand,
        Sand,
        Sand,
        Sand
    },
    {
        OakLogAround,
        OakLogAround,
        OakLogAround,
        OakLogAround,
        OakLogTop,
        OakLogTop
    },
    {
        OakWood,
        OakWood,
        OakWood,
        OakWood,
        OakWood,
        OakWood
    },
    {
        Water,
        Water,
        Water,
        Water,
        Water,
        Water
    },
    {
        OakLeaves,
        OakLeaves,
        OakLeaves,
        OakLeaves,
        OakLeaves,
        OakLeaves
    },
    {
        CactusAround,
        CactusAround,
        CactusAround,
        CactusAround,
        CactusTop,
        CactusTop
    },
    {
        SpruceLogAround,
        SpruceLogAround,
        SpruceLogAround,
        SpruceLogAround,
        SpruceLogTop,
        SpruceLogTop
    },
    {
        SpruceLeaves,
        SpruceLeaves,
        SpruceLeaves,
        SpruceLeaves,
        SpruceLeaves,
        SpruceLeaves
    },
    {
        WinterGrassDirt,
        WinterGrassDirt,
        WinterGrassDirt,
        WinterGrassDirt,
        WinterGrass,
        Dirt
    },
    {
        BirchLogAround,
        BirchLogAround,
        BirchLogAround,
        BirchLogAround,
        BirchLogTop,
        BirchLogTop
    },
    {
        BirchLeaves,
        BirchLeaves,
        BirchLeaves,
        BirchLeaves,
        BirchLeaves,
        BirchLeaves
    }
};

BlockTextures GetBlockTextures(Block block){
    return s_TextureTable[(size_t)block];
}